# Generated by Django 5.0.4 on 2024-04-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lecturer_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_contact', to='main.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='contact',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contact')),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.TextField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contact')),
            ],
        ),
    ]
