# Generated by Django 5.0.4 on 2024-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_lecturer_contact_email_telephonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='claim',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='middle_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='picture_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='price_per_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='title_after',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='title_before',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_student',
            field=models.TextField(null=True),
        ),
    ]
