# Generated by Django 5.0.4 on 2024-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lecturer_bio_alter_lecturer_claim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='contact',
        ),
    ]
