# Generated by Django 5.0.4 on 2024-04-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lecturer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lecturer_uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_contact', to='main.lecturer'),
        ),
    ]
