# Generated by Django 5.0.4 on 2024-04-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_lecturer_uuid_contact_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='main.lecturer'),
        ),
    ]
