# Generated by Django 5.0.4 on 2024-04-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contact_id_alter_contact_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lecturer'),
        ),
    ]
