# Generated by Django 5.0.4 on 2024-04-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contact_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='lecture_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.lecturer'),
        ),
    ]
