# Generated by Django 5.0.4 on 2024-04-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_reservation_lecture_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='telephonenumber',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
