# Generated by Django 5.0.4 on 2024-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_contact_id_email_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telephonenumber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
