# Generated by Django 5.0.4 on 2024-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_email_id_alter_telephonenumber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturetag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
