# Generated by Django 5.0.4 on 2024-04-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subject_rename_notes_reservation_descrition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='descrition',
            new_name='description',
        ),
    ]
