# Generated by Django 5.0.4 on 2024-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_descrition_reservation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('unavailable', 'Unavailable')], default='reserved'),
        ),
    ]
